### ISSUE TITLE
Validate read files against sample input file

### ISSUE THREAD

**Issue by IanGBrennan** [AusARG/pipesnake#2]
### Description of feature

An initial step that would check that all the files specified in the sample input sheet are in the input directory. This would save time by exiting runs that aren't properly configured.

**Comment by IanGBrennan** [comment]
double check that there are no duplicates in the 'lineage' designation of the sample input sheet, as this causes problems downstream.

**Comment by ziadbkh** [comment]
make sure the lineage column has unique values

**Comment by ziadbkh** [comment]
fixed with #bfa144b
