### ISSUE TITLE
Wiki issues

### ISSUE THREAD

**Issue by stiatragul** [AusARG/pipesnake#3]
### Description of the bug

Hey Ian, 

Wanted to make a note here about some parts of the wiki that was unclear. 

As of 2024-01-15 the 
Section 2. Quickstart under 3. Download *pipesnake*

The section for Using singularity may need to be revised. 

**If you are using singularity, please use the [nf-core download](https://nf-co.re/tools/#downloading-pipelines-for-offline-use) command to download images first, before running the pipeline. Setting the [NXF_SINGULARITY_CACHEDIR or singularity.cacheDir](https://www.nextflow.io/docs/latest/singularity.html?#singularity-docker-hub) Nextflow options enables you to store and re-use the images from a central location for future pipeline runs.**

`nextflow run ausarg/pipesnake -profile test,singularity --outdir <OUTDIR>`

Here do you mean to tell the users to first download using `nf-core download ausarg/pipesnake` ? Once the singularity images have been downloaded, then how do the user refer to it? 

Currently the user can just run `nextflow run ausarg/pipesnake -profile test,singularity --outdir <OUTDIR>` 

### System information

    Nextflow version: 23.10.1.5891
    Hardware: Desktop
    Executor: local 
    Container engine: Singularity 
    OS: Linux (Ubuntu 22)

**Comment by IanGBrennan** [comment]
Thanks for those comments Putter.
The instructions for installing `pipesnake` and running with singularity have now changed:
https://github.com/AusARG/pipesnake/wiki/2.-Quick-Start#3-download-pipesnake

I have also included a new section in the Wiki about downloading the pipeline and software container images for offline use:
https://github.com/AusARG/pipesnake/wiki/7.-Offline-Use

Cheers.
