### ISSUE TITLE
Pipeline Flexibility - Running from PRG Stage

### ISSUE THREAD

**Issue by IanGBrennan** [AusARG/pipesnake#6]
### Description of feature

Without making too many changes, it'd be good to have the flexibility to pick up the pipeline at a given stage, e.g. from the PRG stage and proceeding to the end. 

As an example:
I have PRG fasta files from two different projects, but want to do a new project with some samples from each. I could put the sample specific PRG/fasta files of interest into a directory, with a sample info csv file that specifies the lineages and the full path to the files and the pipeline picks up from there. 
modules: phylogeny_make_alignments -->  iqtree --> aster

We could add a parameter to tell the pipeline to jump to a specific step...

**Comment by ziadbkh** [comment]
Please test by passing the input sample sheet in csv format (sample_id, prg_file) and the parameter --stage from-prg

**Comment by IanGBrennan** [comment]
tested and works brilliantly. 

Note: it still requires `--blat_db` even though it doesn't use it, but that's not really a problem. 
Note2: the `prg_file` column must give the full path to the PRG file
